#!/usr/bin/env python3
"""Generate TASKS-GROK.md and TASKS-CLAUDE.md from TASKS.md.

TASKS.md is the source of truth. Every task line starts with an owner tag:

    - [ ] `@grok` **P0-2 · 🔴 · S — Dark form fields are invisible**
      ...indented continuation lines belong to that task...

This splits the board so an agent told "do your tasks" cannot pick up the other
lane's work by accident. Section headings are kept only when the lane actually
has tasks under them, so neither file carries empty scaffolding.

Run after editing TASKS.md:

    python3 scripts/split-tasks.py
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "TASKS.md"

TASK_RE = re.compile(r"^- \[[ x]\] `@(grok|claude)`")
HEADING_RE = re.compile(r"^(#{1,3}) ")

LANES = {
    "grok": ROOT / "TASKS-GROK.md",
    "claude": ROOT / "TASKS-CLAUDE.md",
}

HEADER = """# Rumera — {title} tasks

> **Generated from `TASKS.md` — do not edit this file.** Change `TASKS.md`, then run
> `python3 scripts/split-tasks.py`.
>
> These are **only** the `@{lane}` tasks. The other lane's work is deliberately absent.
> If one of these turns out to depend on a task that is not here, stop and say so
> rather than doing the other lane's work.
>
> Full context — decisions, non-goals, the other lane — is in `TASKS.md`.

{count} tasks · {crit} 🔴 critical · {high} 🟠 high · {med} 🟡 medium

---

"""


def split() -> int:
    if not SOURCE.exists():
        print(f"error: {SOURCE} not found", file=sys.stderr)
        return 1

    lines = SOURCE.read_text().split("\n")

    for lane, out_path in LANES.items():
        kept: list[str] = []
        # Pending headings are only emitted once a task appears beneath them, so a
        # section belonging entirely to the other lane leaves no empty husk.
        pending: list[str] = []
        in_task = False

        for line in lines:
            heading = HEADING_RE.match(line)
            if heading:
                depth = len(heading.group(1))
                # A new heading invalidates any deeper pending headings.
                pending = [h for h in pending if len(HEADING_RE.match(h).group(1)) < depth]
                pending.append(line)
                in_task = False
                continue

            task = TASK_RE.match(line)
            if task:
                if task.group(1) != lane:
                    in_task = False
                    continue
                if pending:
                    if kept:
                        kept.append("")
                    kept.extend(pending)
                    kept.append("")
                    pending = []
                kept.append(line)
                in_task = True
                continue

            # Continuation lines (indented, or blank inside a task block).
            if in_task:
                if line.startswith(("  ", "\t")) or line.strip().startswith("```"):
                    kept.append(line)
                elif line.strip() == "":
                    kept.append(line)
                else:
                    in_task = False

        body = "\n".join(kept).strip("\n")
        count = sum(1 for l in kept if TASK_RE.match(l))
        stats = {
            "count": count,
            "crit": sum(1 for l in kept if TASK_RE.match(l) and "🔴" in l),
            "high": sum(1 for l in kept if TASK_RE.match(l) and "🟠" in l),
            "med": sum(1 for l in kept if TASK_RE.match(l) and "🟡" in l),
        }
        header = HEADER.format(title=lane.capitalize(), lane=lane, **stats)
        out_path.write_text(header + body + "\n")
        print(f"{out_path.name}: {count} tasks")

    return 0


if __name__ == "__main__":
    raise SystemExit(split())
